apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ugent-ingress
  namespace: minio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: minio.jhub.be
   http:
     paths:
     - path: /
       backend:
         serviceName: minio
         servicePort: 9000