journal:
  storageClass: "local-path"

shortCircuit:
  enabled: false
  storageClass: "local-path"

properties:
  alluxio.master.mount.table.root.ufs: s3://mnist/data
  alluxio.underfs.s3.endpoint: http://jhub.be:32000/
  alluxio.underfs.s3.disable.dns.buckets: true
  alluxio.underfs.s3.inherit.acl: false
  aws.accessKeyId: admin
  aws.secretKey: admin
