apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-server-database-config
  namespace: mlflow
  labels:
    app: mlflow-server-database
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123